import { useMemo, useState } from 'react';
import { Copy, Flame, Leaf, MessageCircle, Share2, Sprout, Trophy, Users, Zap } from 'lucide-react';
import { useGarden } from '../../context/GardenContext';

const GrowthHub = () => {
  const { grid, inventory } = useGarden();
  const [buddy, setBuddy] = useState('');
  const [roomStarted, setRoomStarted] = useState(false);
  const [reaction, setReaction] = useState('');
  const sessions = useMemo(() => { try { return JSON.parse(localStorage.getItem('lockin_focus_sessions') || '[]'); } catch { return []; } }, []);
  const totalMinutes = sessions.reduce((sum, session) => sum + Number(session.durationMinutes || 0), 0);
  const weeklyStreak = Math.min(7, new Set(sessions.map((session) => session.completedAt?.slice(0, 10))).size);
  const shareText = `I focused for ${Math.floor(totalMinutes / 60)}h ${totalMinutes % 60}m today · ${weeklyStreak}-day deep work streak`;
  const share = async () => { try { if (navigator.share) await navigator.share({ title: 'My Lock In progress', text: shareText }); else await navigator.clipboard.writeText(shareText); } catch {} };
  const invite = () => { const text = `Join my Lock In focus room: ${window.location.origin}`; try { navigator.clipboard.writeText(text); } catch {} setRoomStarted(true); };
  const seeds = Object.values(inventory).reduce((sum, value) => sum + value, 0);

  return <div className="mx-auto max-w-4xl space-y-6 bg-[#fbfcfb] p-4 sm:p-8">
    <div><p className="text-xs font-black uppercase tracking-[0.2em] text-[#249653]">Growth</p><h1 className="mt-2 text-3xl font-black tracking-tight text-slate-900 dark:text-white">Make progress visible.</h1><p className="mt-2 text-sm text-slate-500">Share momentum, focus with someone, and let consistency become your identity.</p></div>
    <div className="grid gap-4 md:grid-cols-[1.25fr_0.75fr]">
      <div className="rounded-3xl bg-slate-950 p-6 text-white shadow-sm"><div className="flex items-center justify-between"><span className="text-xs font-black uppercase tracking-[0.18em] text-[#8bb99a]">Your progress card</span><Zap className="h-5 w-5 text-[#4dcd7d]" /></div><div className="mt-8 text-3xl font-black">{shareText}</div><p className="mt-3 text-sm text-slate-400">A small start is still a vote for the person you are becoming.</p><button onClick={share} className="mt-6 flex items-center gap-2 rounded-xl bg-[#4dcd7d] px-4 py-3 text-sm font-extrabold text-slate-950 hover:bg-[#70dc98]"><Share2 className="h-4 w-4" /> Share my progress</button></div>
      <div className="rounded-3xl border border-orange-100 bg-orange-50 p-6"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.18em] text-orange-700"><Flame className="h-4 w-4" /> Weekly streak</div><div className="mt-5 text-5xl font-black text-orange-950">{weeklyStreak}<span className="ml-2 text-lg">days</span></div><p className="mt-2 text-sm font-semibold text-orange-800">Build a streak worth showing.</p><div className="mt-5 flex gap-1.5">{Array.from({ length: 7 }, (_, index) => <div key={index} className={`h-2 flex-1 rounded-full ${index < weeklyStreak ? 'bg-orange-500' : 'bg-orange-200'}`} />)}</div></div>
    </div>
    <div className="grid gap-4 md:grid-cols-2">
      <div className="rounded-3xl border border-[#d9f1df] bg-[#eaf8ee] p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-sm font-black text-[#249653]"><Sprout className="h-5 w-5" /> Garden snapshot</div><span className="text-xs font-bold text-[#249653]">{grid.filter(Boolean).length} growing</span></div><div className="mt-6 text-4xl">🌱 🌿 🪴</div><p className="mt-4 text-sm font-semibold text-slate-600">{seeds} seeds collected. Share your garden with a buddy after your next session.</p></div>
      <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-2 text-sm font-black text-slate-800 dark:text-white"><Trophy className="h-5 w-5 text-amber-500" /> Small leaderboard</div><div className="mt-5 space-y-3">{[['You', totalMinutes], ['Maya', 185], ['Rafi', 140]].sort((a, b) => b[1] - a[1]).map(([name, minutes], index) => <div key={name} className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2 text-sm dark:bg-slate-800"><span className="font-bold text-slate-700 dark:text-slate-200">#{index + 1} {name}</span><span className="font-black text-[#249653]">{minutes}m</span></div>)}</div></div>
    </div>
    <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between"><div><div className="flex items-center gap-2 text-sm font-black text-slate-800 dark:text-white"><Users className="h-5 w-5 text-[#249653]" /> Focus Room</div><p className="mt-1 text-xs text-slate-500">One useful connection. No noisy social network.</p></div><span className={`rounded-full px-3 py-1 text-[10px] font-black ${roomStarted ? 'bg-[#eaf8ee] text-[#249653]' : 'bg-slate-100 text-slate-400'}`}>{roomStarted ? 'Room ready' : 'Waiting for a buddy'}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-[1fr_auto]"><input value={buddy} onChange={(event) => setBuddy(event.target.value)} placeholder="Buddy name or email" className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-sm outline-none focus:border-[#4dcd7d] dark:border-slate-700 dark:bg-slate-800 dark:text-white" /><button onClick={invite} className="rounded-xl bg-[#4dcd7d] px-4 py-3 text-sm font-extrabold text-slate-950 hover:bg-[#70dc98]"><Copy className="mr-2 inline h-4 w-4" />Invite to focus</button></div>{roomStarted && <div className="mt-5 rounded-2xl bg-slate-50 p-4 dark:bg-slate-800"><div className="flex items-center justify-between text-sm"><span className="font-bold text-slate-700 dark:text-slate-200">You · focusing</span><span className="text-xs font-bold text-[#249653]">{totalMinutes ? 'session active' : 'ready to start'}</span></div><div className="mt-3 flex gap-2"><button onClick={() => setReaction('Keep going!')} className="rounded-lg bg-white px-3 py-2 text-xs font-bold text-slate-600 shadow-sm dark:bg-slate-900">💪 Keep going</button><button onClick={() => setReaction('Nice work!')} className="rounded-lg bg-white px-3 py-2 text-xs font-bold text-slate-600 shadow-sm dark:bg-slate-900">✨ Nice work</button>{reaction && <span className="flex items-center gap-1 text-xs font-bold text-[#249653]"><MessageCircle className="h-3.5 w-3.5" /> {reaction}</span>}</div></div>}</div>
  </div>;
};

export default GrowthHub;
