import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Check, ChevronDown, Circle, Flag, Plus, Users } from 'lucide-react';

const starter = [
  { id: 'launch', name: 'Product launch', goal: 'Ship a calm, focused launch', owner: 'You', deadline: 'Oct 30', status: 'In progress', priority: 'High', milestone: 'Launch preparation', tasks: [{ id: 1, title: 'Write launch announcement', done: false, minutes: 45 }, { id: 2, title: 'Review launch metrics', done: true, minutes: 30 }] },
  { id: 'antartica', name: 'Antartica', goal: 'Plan the next expedition clearly', owner: 'You', deadline: 'Nov 14', status: 'Planned', priority: 'Medium', milestone: 'Research and route', tasks: [{ id: 3, title: 'Collect route references', done: false, minutes: 30 }, { id: 4, title: 'Draft the first plan', done: false, minutes: 45 }] },
  { id: 'hail-mary', name: 'Hail Mary', goal: 'Turn the ambitious idea into a first step', owner: 'You', deadline: 'Dec 01', status: 'Inbox', priority: 'High', milestone: 'Define the outcome', tasks: [{ id: 5, title: 'Write the project brief', done: false, minutes: 25 }] },
];
const STATUSES = ['Inbox', 'Planned', 'In progress', 'Done', 'Blocked', 'Someday'];

const ProjectsPage = () => {
  const [projects, setProjects] = useState(() => { try { const saved = JSON.parse(localStorage.getItem('lockin_projects') || 'null'); if (!saved) return starter; const missing = starter.filter((seed) => !saved.some((project) => project.id === seed.id)); return [...saved, ...missing]; } catch { return starter; } });
  const [activeId, setActiveId] = useState(projects[0]?.id);
  const [newProject, setNewProject] = useState('');
  const [newTask, setNewTask] = useState('');
  const active = projects.find((project) => project.id === activeId) || projects[0];
  useEffect(() => localStorage.setItem('lockin_projects', JSON.stringify(projects)), [projects]);
  const completed = active?.tasks.filter((task) => task.done).length || 0;
  const progress = active?.tasks.length ? Math.round((completed / active.tasks.length) * 100) : 0;
  const updateActive = (updater) => setProjects((current) => current.map((project) => project.id === active?.id ? updater(project) : project));
  const addProject = (event) => { event.preventDefault(); if (!newProject.trim()) return; const project = { id: Date.now().toString(), name: newProject.trim(), goal: 'Define the outcome for this project', owner: 'You', deadline: 'Set deadline', status: 'Inbox', priority: 'Medium', milestone: 'First milestone', tasks: [] }; setProjects((current) => [project, ...current]); setActiveId(project.id); setNewProject(''); };
  const addTask = (event) => { event.preventDefault(); if (!newTask.trim() || !active) return; updateActive((project) => ({ ...project, tasks: [...project.tasks, { id: Date.now(), title: newTask.trim(), done: false, minutes: 25 }] })); setNewTask(''); };
  const toggleTask = (id) => updateActive((project) => ({ ...project, tasks: project.tasks.map((task) => task.id === id ? { ...task, done: !task.done } : task) }));

  return <div className="mx-auto max-w-6xl space-y-6 bg-[#fbfcfb] p-4 sm:p-8">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#249653]">Workspace</p><h1 className="mt-2 text-3xl font-black tracking-tight text-slate-900 dark:text-white">Projects</h1><p className="mt-1 text-sm text-slate-500">Turn a big outcome into today’s next step.</p></div><form onSubmit={addProject} className="flex gap-2"><input value={newProject} onChange={(e) => setNewProject(e.target.value)} placeholder="New project" className="w-40 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:border-[#4dcd7d] dark:border-slate-700 dark:bg-slate-900 dark:text-white" /><button className="rounded-xl bg-[#4dcd7d] px-3 py-2 text-xs font-black text-slate-950"><Plus className="mr-1 inline h-4 w-4" />Create</button></form></div>
    <div className="space-y-6 [&>aside]:grid [&>aside]:grid-cols-1 [&>aside]:gap-4 [&>aside]:space-y-0 sm:[&>aside]:grid-cols-2 lg:[&>aside]:grid-cols-3">
      <aside className="space-y-2">{projects.map((project) => <button key={project.id} onClick={() => setActiveId(project.id)} className={`w-full rounded-2xl border p-4 text-left transition ${project.id === active?.id ? 'border-[#4dcd7d] bg-[#f0fbf3] shadow-sm' : 'border-slate-200 bg-white hover:border-[#bcebc9] dark:border-slate-800 dark:bg-slate-900'}`}><div className="flex items-center justify-between"><span className="text-sm font-black text-slate-800 dark:text-white">{project.name}</span><ChevronDown className="h-4 w-4 text-slate-400" /></div><div className="mt-2 text-xs text-slate-500">{project.tasks.filter((task) => task.done).length}/{project.tasks.length} tasks · {project.status}</div><div className="mt-3 h-1.5 rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-[#4dcd7d]" style={{ width: `${project.tasks.length ? (project.tasks.filter((task) => task.done).length / project.tasks.length) * 100 : 0}%` }} /></div></button>)}</aside>
      {active && <main className="space-y-5"><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold text-[#249653]">Project workspace</p><h2 className="mt-1 text-2xl font-black tracking-tight text-slate-900 dark:text-white">{active.name}</h2><p className="mt-1 text-sm text-slate-500">{active.goal}</p></div><div className="text-right"><div className="text-3xl font-black text-[#249653]">{progress}%</div><div className="text-[10px] font-bold uppercase tracking-wider text-slate-400">complete</div></div></div><div className="mt-5 h-2 rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-[#4dcd7d] transition-all" style={{ width: `${progress}%` }} /></div><div className="mt-5 grid gap-3 sm:grid-cols-4"><div><div className="text-[10px] font-bold uppercase text-slate-400">Status</div><div className="mt-1 text-sm font-bold text-slate-700 dark:text-slate-200">{active.status}</div></div><div><div className="text-[10px] font-bold uppercase text-slate-400">Priority</div><div className="mt-1 text-sm font-bold text-amber-600">{active.priority}</div></div><div><div className="text-[10px] font-bold uppercase text-slate-400">Owner</div><div className="mt-1 text-sm font-bold text-slate-700 dark:text-slate-200"><Users className="mr-1 inline h-3.5 w-3.5" />{active.owner}</div></div><div><div className="text-[10px] font-bold uppercase text-slate-400">Deadline</div><div className="mt-1 text-sm font-bold text-slate-700 dark:text-slate-200"><CalendarDays className="mr-1 inline h-3.5 w-3.5" />{active.deadline}</div></div></div></section>
        <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-2"><Flag className="h-4 w-4 text-[#249653]" /><h3 className="text-sm font-black text-slate-800 dark:text-white">{active.milestone}</h3><span className="ml-auto text-xs font-bold text-slate-400">{completed}/{active.tasks.length}</span></div><div className="mt-4 space-y-2">{active.tasks.map((task) => <div key={task.id} className="flex items-center gap-3 rounded-2xl bg-slate-50 p-3 dark:bg-slate-800/60"><button onClick={() => toggleTask(task.id)} className={`flex h-5 w-5 items-center justify-center rounded-full ${task.done ? 'bg-[#4dcd7d] text-white' : 'border border-slate-300 text-transparent'}`}>{task.done ? <Check className="h-3.5 w-3.5" /> : <Circle className="h-3.5 w-3.5" />}</button><span className={`flex-1 text-sm font-semibold ${task.done ? 'text-slate-400 line-through' : 'text-slate-700 dark:text-slate-200'}`}>{task.title}</span><span className="text-xs font-bold text-slate-400">{task.minutes}m</span></div>)}</div><form onSubmit={addTask} className="mt-4 flex gap-2"><input value={newTask} onChange={(e) => setNewTask(e.target.value)} placeholder="Add task or subtask" className="flex-1 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm outline-none focus:border-[#4dcd7d] dark:border-slate-700 dark:bg-slate-800 dark:text-white" /><button className="rounded-xl border border-[#bcebc9] px-3 py-2 text-xs font-black text-[#249653]"><Plus className="mr-1 inline h-3.5 w-3.5" />Add</button></form></section>
      </main>}
    </div>
  </div>;
};

export default ProjectsPage;
